### PR TITLE
Fix: Function List proper Open in Editor handling [master]

### LINKED ISSUE #313: Confusing Function List behavior with Open in Editor: Preserve active document
Normally, the contents of Function List are updated when the editor tab selection is changed. However, when a document is open by the OpenInEditor step, and the "Open in Editor: Preserve active document" option is enabled, the tab focus does not change but the Function List is still updated, leading to confusing behavior where FL displays the contents for an inactive tab and moving the cursor in the active document does not refresh it:

FL

### PR DESCRIPTION
**Pull request by johnny-keker**
Resolves #313 

Added additional things so #301 would work for `master`.

### CODE REVIEW

**Comment by johnny-keker** [comment]
Resolves #313

**Comment by Kirpich30000** [comment]
Hmmm..., there is #316 which is supposed to address #313
Could you please check which PR should be used to solve #313?

**Comment by johnny-keker** [comment]
> Hmmm..., there is #316 which is supposed to address #313 Could you please check which PR should be used to solve #313?

I believe that #316 is supposed to resolve #303, while this PR resolves #313

**Comment by Kirpich30000** [comment]
Ok, thanks for the clarification

**Pull request merged**
