### PR TITLE
[example] support vector add with size > 64

### PR DESCRIPTION
**Pull request by B1tway**
This PR updates the kernel with workgroup support for the host machine project

### CODE REVIEW

**Comment by Slimakanzer** [comment]
@B1tway kernel changes LGTM.
However, recently #233 PR with some _Example project_ changes was merged into _dev-stable_.
Can you redo this PR on top latest changes?

Most likely you will need:
- Add _length_ [option](https://github.com/vsrad/radeon-asm-tools/blob/d465d37fdef48f048d2bbcfe3492d8933427fe5e/Example/VectorAddProjectExample/gfx9/fp32_v_add.cpp#L251-L255) and [pass](https://github.com/vsrad/radeon-asm-tools/blob/d465d37fdef48f048d2bbcfe3492d8933427fe5e/Example/VectorAddProjectExample/gfx9/fp32_v_add.cpp#L73) this value.
- Change [grid size](https://github.com/vsrad/radeon-asm-tools/blob/d465d37fdef48f048d2bbcfe3492d8933427fe5e/Example/VectorAddProjectExample/gfx9/fp32_v_add.cpp#L160)
- Apply your changes to the **_fp32_v_add_** kernel

**Review by Slimakanzer — CHANGES_REQUESTED** [review]
@B1tway kernel changes LGTM.
However, recently #233 PR with some _Example project_ changes was merged into _dev-stable_.
Can you redo this PR on top latest changes?

Most likely you will need:

- Add [length](https://github.com/vsrad/radeon-asm-tools/blob/d465d37fdef48f048d2bbcfe3492d8933427fe5e/Example/VectorAddProjectExample/gfx9/fp32_v_add.cpp#L251-L255) option and [pass](https://github.com/vsrad/radeon-asm-tools/blob/d465d37fdef48f048d2bbcfe3492d8933427fe5e/Example/VectorAddProjectExample/gfx9/fp32_v_add.cpp#L73) this value.
- Change [grid size](https://github.com/vsrad/radeon-asm-tools/blob/d465d37fdef48f048d2bbcfe3492d8933427fe5e/Example/VectorAddProjectExample/gfx9/fp32_v_add.cpp#L160)
- Apply your changes to _the fp32_v_add_ kernel

**Comment by B1tway** [comment]
Done

**Review by Slimakanzer — APPROVED** [review]
LGTM

**Pull request merged**
