### PR TITLE
Visualizer fixes

### PR DESCRIPTION
**Pull request by johnny-keker**
Addresses #130 
Addresses #133 

* Fixed reordering issue - after adding a new watch it was impossible to change its position
* Removing empty brackets from watch name

### CODE REVIEW

**Review by Slimakanzer — APPROVED** [review]
LGTM, works as expected!
* Tried to use `AddToWatches` with empty square brackets
* Tried to use `AddToWatches` with not empty square brackets
* Tried reorder watches in different situations like after adding, after deleting, after successful debug result, after invalid debug result and etc.

**Review by Slimakanzer — CHANGES_REQUESTED** [review]
It would be nice to implement removing empty brackets in the `ActiveCodeEditor.GetActiveWord()`. In this case, you will not need to use an dte instance, switch to main thread and check selected text again.

**Comment by johnny-keker** [comment]
> 
> 
> It would be nice to implement removing empty brackets in the `ActiveCodeEditor.GetActiveWord()`. In this case, you will not need to use an dte instance, switch to main thread and check selected text again.

Thanks for the suggestion, implemented in 4b7335b

**Review by Slimakanzer — APPROVED** [review]
LGTM

**Pull request merged**
